apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    hpa-overlay-full-path: qa/consumer/event-consumer/main/patches
  labels:
    dir: therma-flux-apps
  name: therma-event-consumer
spec:
  maxReplicas: 6
