apiVersion: apps/v1
kind: Deployment
metadata:
  name: therma-gateway-offline-consumer
spec:
  template:
    spec:
      containers:
        - name: application
          resources:
            limits:
              cpu: 100m
              memory: 800Mi
            requests:
              cpu: 100m
              memory: 200Mi
