apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: therma-location-api-service-qa
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: therma-flux-apps-main-with-monitoring-bases
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: devops@hellotherma.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./qa/api/location-api-service/
    strategy: Setters
