apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: therma-test-api
  namespace: beta
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: therma-test-api
  targetCPUUtilizationPercentage: 80
