apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecobee-data-consumer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: application
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 300m
              memory: 500Mi
