apiVersion: apps/v1
kind: Deployment
metadata:
  name: therma-mqtt-amqp-bridge
spec:
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 300m
            memory: 500Mi
