apiVersion: apps/v1
kind: Deployment
metadata:
  name: therma-energy-api-gateway
spec:
  template:
    spec:
      containers:
        - name: application
          image: mewe/therma-energy-api-gateway:develop_ce46100ac173e8111b6bf479363167becb10be2e_20230622003730 # {"$imagepolicy": "development:therma-energy-api-gateway"} 
