apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ds-job-scheduler
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ds-job-scheduler
              image: mewe/rabbitmq-client:develop
