apiVersion: v1
data:
  ACCOUNT_API: http://therma-account-api-service.beta.svc.cluster.local
  ALERT_API: http://therma-alert-api-service.beta.svc.cluster.local
  ALERT_SERVICE: "http://therma-alert-service.beta.svc.cluster.local."
  API_SERVICE: http://therma-api-service.beta.svc.cluster.local
  AUDIT_LOG_API: http://therma-audit-log-api-service.beta.svc.cluster.local
  CALIBRATION_INTERNAL_API: http://therma-calibration-internal-api-service.beta.svc.cluster.local
  CALIBRATION_PUBLIC_API: http://therma-calibration-api-service.beta.svc.cluster.local
  CHIRPSTACK_ENDPOINT: "https://chirpstack.stg.helloatka.com/api"
  DATA_API: http://therma-data-api-service.beta.svc.cluster.local
  DEVICE_API: http://therma-device-api-service.beta.svc.cluster.local
  DEVICE_SERVICE: "http://therma-device-service.beta.svc.cluster.local."
  EQUIPMENT_SERVICE: "http://therma-equipment-service.beta.svc.cluster.local."
  LOCATION_API: http://therma-location-api-service.beta.svc.cluster.local
  PROMETHEUS_ENDPOINT: http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1
  REPORT_API: http://therma-report-api-service.beta.svc.cluster.local
  THERMALINK_API: http://therma-thermalink-api-service.beta.svc.cluster.local.
  CLIMATE_SERVICE: http://therma-climate-service.beta.svc.cluster.local
kind: ConfigMap
metadata:
  name: api-endpoints
