apiVersion: v1
data:
  INFLUXDB_HOST: influxdb-sensor-data.beta.svc.cluster.local
  INFLUXDB_NAME: therma_beta
  INFLUXDB_USERNAME: therma_beta_admin
  INFLUXDB_PORT: "8086"
  INFLUXDB_PROTOCOL: http
kind: ConfigMap
metadata:
  name: influxdb-config
