apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-storage-consumer
spec:
  template:
    spec:
      containers:
        - name: application
          image: mewe/influxdb-storage-consumer:release_97f897477ddf122b426176a25ab0f3ad7748c2e3_20230511210943 # {"$imagepolicy": "beta:influxdb-storage-consumer"}  
