apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: therma-audit-log-api-service-beta
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: therma-flux-apps-main-with-monitoring-bases
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: devops@hellotherma.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./beta/api/audit-log-api-service
    strategy: Setters