apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: test-deployment-changes-consumer
  namespace: qa
spec:
  maxReplicas: 4
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment-changes-consumer
  targetCPUUtilizationPercentage: 80
