apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: savings-generator
  labels: 
    dir: "therma-energy-flux-apps"
  annotations:
    hpa-overlay-full-path: "beta/internal-apis/savings-generator/main/patches"
spec:
  maxReplicas: 5
  
