apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-generator
spec:
  template:
    spec:
      containers:
        - name: application
          image: mewe/savings-generator-service:develop_5da9a170729d07cbe3f9fb9a266d865db8d982f9_20230713151905 # {"$imagepolicy": "development:savings-generator"} 
