apiVersion: apps/v1
kind: Deployment
metadata:
  name: therma-smart-alert-consumer
spec:
  template:
    spec:
      containers:
        - name: application
          image: mewe/atka-smart-alert-consumer:release_a215fe2cec89aa64ed894e4787e3ba1698ea3edf_20230718010044 # {"$imagepolicy": "beta:therma-smart-alert-consumer-beta"} 
          imagePullPolicy: Always
