apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-task-consumer
spec:
  template:
    spec:
      containers:
        - name: application
          image: mewe/therma-energy-task-consumer:release_7a31576cfa3d1b90116c1409c02a74720c29ff6b_20230727194709 # {"$imagepolicy": "beta:energy-task-consumer"} 
