apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: therma-energy-daily-weather-api-scheduler
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: therma-energy-daily-weather-api-scheduler
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  cpu: 1000m
                  memory: 800Mi
