namespace: beta
resources:
  - ./image-policy.yaml
  - ./image-automation.yaml
  - ../../../../energy-bases/external-apis/therma-energy-webhooks/main
patchesStrategicMerge:
  - ./patches/resources.yaml
  - ./patches/image.yaml
  - ./patches/ingress.yaml
  - ./patches/hpa.yaml
