apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: mewe/therma-energy-ecobee-data-consumer:release_58532559d1026460866ec0cfa6c99b675723f4cb_20230705162650 # {"$imagepolicy": "beta:ecobee-data-consumer"} 
