apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: energy-api-keys
  namespace: beta
spec:
  encryptedData:
    UTILITY_API_KEY: AgA6xGuMyqqj2KYIuNguBLfxKnb4vyo7KmSaNVFi5RZy8H6zFMgEmsfPXYXwX9HJ/CFUNtHM5Y8d1gAqOFDsKuIYOVsHMQ2wWCc8w3XwH2bq5csvk2vLaMeQQ7+G3meCtsCItMgyRRCHHU32w/zvRmV08nZCr1JsIW6an6rIY5kPp8WKyWgsWIjPsTd06oQiHakIYnZ2hvsOj0PRRJn2IGLFxHU5CfEyETeDhLCwomG/jWwGt4vrNq/x92yMx1ghV8MbzHHlbwxdWVGflFQCu4ROxTeD15Wkk09JaJlzE4Pnf1vEc2DLs3eMq4vntCcWxBracu7AK01UbMta2Bh3G71rlZvh4WzynG3pDRGfjUOe9uHz37g+4WYvU+Sw3vQsQaeGkF0Gaml6V6fkcvlvWf/2w+ftPC8hvqy5PFSvAlLhlubsLqqC46w3cXnf4JnX/pDHgHTQsRylg0mIemH+F2EE4rZFZxbyUzkNyjCHzyWetGIalMvvopRwOIfuw7/82IXIQ3ADtSHBTspj3LT3VexTnLft2vfT00yCM1uamywcXw+s3R9GB7FJfrTLMhndxZcX79q3VJtd9nspz/1unyBwFKxSmwNJC5Fy5x/I+aHhjjEB4fBOD/RMwPMtL0/5jz2QDii+3uvOrzhuSGe16wcYU7+/sbcEP537uk//YbccyHFeM3Oh5UPt9ebl+Q1nte5ZUfb+nDjV3omI5V1aLZDX7y33W1H4ThOQNVeID+3Sew==
    WEATHER_ENERGY_API_KEY: AgCjR7dxpxQ0alxAF+BFE5kj5h8j6wVBUe4tX/uKcSDIDkehzcAbRKgbTc3b2MMmLRNtLtd0bgJOjQHcXpb6y7fRUe3MEz19P6ZtxroHiv72x9d5gJj4zltAvChk2ELiF+ZhRxIhmFXo+mbf/kGg4W1TT+goRhUD3rLZuPtPJW8jzLM99cTbDhbR01eobGqFCyDfBNSqfUAHmyGme/s/vFPiZmUmAbrXnMsK0YRmdtfLjCR4J6eMa1UCnQz7sbDhru59x8H9ChYpDwd7C4CXdIg1wS88GEtXBEfO8ZGtNQ3ngNhbDjY+bSupgWwQOE2moJ3zLqBD7UTkHV9NZPtUYjgCxhu7nM7tOzuJiwv3CjkZRy7QOqUHCwmnB43xn7MqCKuHnv7KRqQP5ad6qld+tw/IpCcGpPOuq8r2anrpz35az7wOYBDTl27ZBL7A0cN0JcINBjFJ4jz7zLdhJsDdIhm1ISuc4fccL9W7q9jO0J/fNhE4xw42th+QsMdPCKhOOo7wHXPebozp5kzlvjtoa86Uo+WJo7lfG6FMmvuPZ5YCYQuMgXbD7nOfdozLxZateTsBLGEBmyndui/p5rWxYqWQAalrZ3Lpx/TYA+0Bt7UAy70KPGY+nP3Z9Vx3Efkk6FirJxo8auaVaTv1gqM2ZBb2EhFdzotV1RQ5Rt7Sunwi9Uwq7Lsrcn/lG00XguLoC49QX3PSyuCJe6NHm4PxibG4ldX6uK1+ZU7A
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: energy-api-keys
      namespace: beta

