apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    hpa-overlay-full-path: beta/consumers/demand-response-consumer/main/patches
  labels:
    dir: therma-energy-flux-apps
  name: demand-response-consumer
spec:
  maxReplicas: 6
