apiVersion: apps/v1
kind: Deployment
metadata:
  name: therma-thermalink-api-service
spec:
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi