apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: therma-energy-api-gateway
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: therma-energy-flux-apps-main-with-energy-bases
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: devops@hellotherma.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./beta/external-apis/therma-energy-api-gateway
    strategy: Setters
