apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: mewe/therma-energy-shelly-command-consumer:release_9ae3076e604aa48185cdc1cf3d36cb95253fd922_20230421194840 # {"$imagepolicy": "beta:shelly-command-consumer"} 
