apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-generator
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: application
          image: mewe/therma-energy-apis:develop_badf2f79e4715dc9579f7ca261a3db18ac707893_20230707162610 # {"$imagepolicy": "development:therma-energy-apis"} 
          resources:
            limits:
              cpu: "1"
              memory: 600Mi
            requests:
              cpu: 300m
              memory: 100Mi
