namespace: beta
resources:
  - ./image-policy.yaml
  - ./image-automation.yaml
  - ../../../../energy-bases/consumers/ecobee-data-consumer/main
patchesStrategicMerge:
  - ./patches/resources.yaml
  - ./patches/image.yaml

