apiVersion: apps/v1
kind: Deployment
metadata:
  name: therma-energy-apis
spec:
  template:
    spec:
      containers:
        - name: application #TODO
          image: mewe/therma-energy-apis:master_21a8cf04bd08c21c2baefe4cdc8ecc574331926c_20230707155645 # {"$imagepolicy": "production:therma-energy-apis"} 
