apiVersion: apps/v1
kind: Deployment
metadata:
  name: therma-equipment-service
spec:
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 300Mi
