apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecobee-command-consumer
spec:
  template:
    spec:
      containers:
        - name: application
          image: mewe/therma-energy-ecobee-command-consumer:release_0b851b9553ca1a3deab73d74506eab4f63ca1db9_20230815214723 # {"$imagepolicy": "beta:ecobee-command-consumer"} 
