apiVersion: apps/v1
kind: Deployment
metadata:
  name: therma-alert-config-reminders-scheduler
spec:
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            cpu: 1000m
            memory: 800Mi
          requests:
            cpu: 300m
            memory: 500Mi
