apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gcp-keys
  namespace: beta
spec:
  encryptedData:
    GOOGLE_API_KEY: AgCIEDGOKaoBoadg/ddG0PmgzYn6zkOZIgvMdkKHtPCTSZJUgAbuMcJbN9+wxWVHOAPXgyTIOSNLUrxURwtXKy4zmogZIRqOPz9y1KzCN900abihpNd9v0dn6MHT9XFcTkinhBeE8LiOe+weVZIBNtzZj4lRDZb5mPYpgU2S38LOkg8d4ygQW3J1jol/amQ4mlUc8sXscxBdns13Q9y5EJiYjgn/34y8ZV92Mf54wx+gNWUR7TUqy9aC/axT5UZsaFPFQwN4TEMyRv0ZEtmdzl/imbmtl0t+5twAYM4KbXeZAjPqnvqlb8nSEaYHK61pgCw9H1acY01AjNV29Oy9hBCEJ++aCZHypzTjfrzltcdcyPeQsheKolK///+qdZDcXelSlAOoK4HfEQ5DuIn5BgLNosm1Cx61F7HTIT2difK0WkXTYHshvYFFGdvd0VLKbwBNRBuGaxAmfUj8lBKxS14TFiOeC4NDJTGJZntkAj8rIlMOU5xFF/Sc0l4rqNGP6YiEOMnORU2j5mDRda0Ne/hjnVpGW/LupZ8GD7y6gPNmyndQ4E28x14uoezzavFV9GX4K9ePJ4tPdkgbcDZlHwTKqg7a/io83teOZ2LjYLcIsqfvsYpWFChcnuVG9AAtaUXiZ4WbEmMDVwa4Prl9+pI1CKilN31N5vSrUBZyk/nAQRZjvMub09kwk7Pnh/486glwB5qsy8OecNgtCDV8SydrFjpvbtsEEm7Gp1Y1YiCab4gBojSzOAk=
    GOOGLE_MAP_API_KEY: AgBISz+pifzHzCS2ZQuVjsgYJksGT2glgVtPjmxTl5kgP5m/sPiZy+5CTXxgkh5X9MW+vqvUrZN2Yd/8Gd/mhUq5wZb/92pGKtFy90s+U/lBPbRKvc321WBQAgj62kVcj5u/Pz+xOGJuRmU+81l9vnEu93y1cRkGvFWybmikPV79gV8QQi1XcH4pTYKx9hIgZVmQZhmSeF18NbW7fJiVp9Bi9KbtjGKExJWr1yGRJ0yfkAHZjqjZ34mvJGsyeMkM0GvYoDa5ARAYHHnzX6qzBEM6elwdgRRIuMjUM3HCaVjKLKjpViQNcNvvcGD7w8t5p2fG3OYbBetSX5i8LLlle8JUgkm54AVGbBBHmsbcmyJjCk4HrziQM/5/UHHQr+gHfyGjK9N1NQ9qR8WEXpRtfSN+qgSaSRu6I81dCbO5rKSQtBrmGqj/D5i32kl8EFoa+i5hXP2oDjL4z23KLg1URX1U7imFZT10J0dIm1HhG3gi8XuDJTXHAnI5IyRaH6rZrSjfAHj5UxjGJ8GaJNlRp7F2yi77+upF4HVGrewdCB2ZQYhSKQQQOGqCRNhbAlYMF5V3RanvAWINW7F5V76UjnsWzdUEtGRDmZ3GpuptVR3T25zYBAomWLJ7NkD2hqw+j08BmTWd+cx4f8jpy49FqbvRfHi/swJrIw4JYy/YApT/5CTtugy2dl2ugHByoWVf0oohV+SZrqaBuw8c322i/ScQNwHE/KVje3Gln7PWN5UeVdDD9f18teM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gcp-keys
      namespace: beta
    type: Opaque

