apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-keys
  namespace: beta
spec:
  encryptedData:
    INFLUXDB_PASSWORD: AgDFA0F+rz1WWzcp3qa0oj3bvTOB9SLkApVzwXoDJ+UqjgGBAddJVfPTX6w3ibMf5Fue9/3I3pMBVvz8Y6g1SEB9V2TCwgUeSvkXGODlPLisEobR9gWwtkYoDQmNNtxFxhSJtzZF+JbBX5Ad56FCxz4tTFt1Nh5ZbLo79g2QQdrKeHMmyWvqdJLNRlIrL4KT8uL/dLnyn1cQSHPhjm7JigkO2ynMmF62djqSC7qodkdiNZgUmmNc+85NZolxj2jWZUhr74brmJbpXgYteg80DiZbKf950RfqM+nph3O6oVrprqwjF9aud8r71wpqfGP4XSOJE+xzmhIX+PhyTTDDpdqZEHIvQr2rfymBhQ5ZDhvC4MOuC8UI0FT+INRKQm9775dJaPv+6GI5IA7q7+ZTkzvsUk4qaPjTCa3tCiwiK1D5jvd9Zxx4CSXooc3UvHSt7h54yPA3g0litWIAkhMYT30kwy4v0470wA5+Jc9G0s/EVWG2FilMHw4QFN6C7EJqjnkdRETwPkHfEBv8dJ3fzeGAF6KY7BdNKboOQiTGhZ9O8HrPX8r/+tq05u1bvyERglS1LjrnUU1KKCRMepCzuHPp2KF6UkKFbO0593a6IeG4X4R+ynKTIop54V8UgzUF0T5MWoX83eovfkKqHxXbc9bj8+Cp7LKNAEbZbBJnBs/ulLHj9IirX3Itl+P1bjnMtxEDEIFmDqWGs/X+
    INFLUXDB_USER: AgAlPNHgVMAgPqmQU9uiq1D3/P2Ot58UIEgCTLgcHVZUi99MRi7z3sNUUOp20IP06/kX4i5qFJlxbl9UdpSPGCKpPFe0kaB6MsZfn1uD4D0oWp9xf6R6p5kOp5rfEjTgEcg3NpOH/fnI9FcHvsCNHl8Fe3GQesbPhHcbnwIDgwq+Oxf5UTNBFghY/8OhhwZJLgUOr9uy+KmmqmPz5HkQp8oJRXv4nEBtvoioQtLS4tOJENDACQWPVPABB8CmqvRcfyhenlIB03ZyF6xWZCqnoExrdivchSgAdRYm8lHEICDF3oNuwfbNPi7eUz8dBTpGh7hXalOZCDpNLzc3XTf9IcgKlUOYPptSLFOJUxXkQoK0y+6fGvy7rnEZf0wm2Z2lgXOvp9dHxN2y2lZwpUyT22U7/NeSeLhKI1QrlnpYWKU9zUEtInIr5t6H2aE457Vrs2khgAbS68IpgklnkmcRci14qLTG7sM9/rS1Gmuj0vbrtzxxSxYTlr6FIir7NglwjGPZ9qsDeSRB1zSo7PWE/QB5OMj2QuRf5bA4V+8tcOW3osigZGinrghHP9t8A1Tx23zX7AEADUAGw8/YUrttUtJ22cyHnzYApEzRuSka0v6SNKndzf4pr/W4mmdq/votg73w1rCeM0q8cfBFfpzs3+q4/bJ79I1PuocUWsgg6kE3yZEa27XlzXj1mFqLWbj66P+W8KZWUcy0v/xsaOPCYq7GDQ==
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-keys
      namespace: beta
    type: Opaque
