apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: amqp-credentials
  namespace: beta
spec:
  encryptedData:
    MONITORING_AMQP_PASSWORD: AgC9ITStz48/W6DiPtRO39Paal+SpgwkWyHXmfhXllqgbypq6yTEZAc02j1wre9kzOR+aAlyQfXEeaZHprDKFVCzDogwreBz+QSkHpvzA8rGTK4M/cM1ONKsxq2P6/AYjzhDIuGNHF2+mP2p4aPjaBRA8/B6MyRHKHh5GHnyuMhbWxd1ei6ltzdQXAp1UFgA37zue00i/Bm08WsIuadze7WR9Nw2RARjjbF7L3iO1VI2mFGzr5W63J75ssVKmUaTkL5JzwuEqBg7Zt9vD/bzIxD4s/w4/AxPfXXIh9f/U6h5YwcZNMvQavMveZwED9obGySr4WMVHKtmYLue8OG3U4JnH36AEMKLgw46nWHJ4Ib86di3HSqucGaIbbqW32FgohNVN7NiChqDpL74EgnroHYXQArQeFnO7ux5PfPf3XPsrowOsc4m+MXvv7yIKrxSCnZPCMxgpiGjn6tDMeJ9o26Ma3rEY611UTpUr+rJ9vAcEPU0sm8aLlQr6VN4tSxAzCsn8WDC/r5WaWdIsEFxfRfcVwWbRcxuTcTQPwHP3FE4N7fqL7CbbLUsJ79D0UU4MFChPbwDppz3XF/R8iOrIoiELf0U2EiEr9vVDm6rlCcSkkt4ClDHa+fS9Tq/0Bxgf7vvST1nEpvXJ+TRfwpbyQYYvuVgR6AOOzSeDQuOVjNnfukAna3DkZnVddplJTmqr4ScfndRxf1UFiST
    HARDWARE_AMQP_PASSWORD: AgC1829Bk2/ORUWTw5uLSRRQxgTPyWWEyNnwlOEYlpADqlgGk1ACe+qMsPdlugLquHoO4c8QOiHnmLHSms8f5/Ct0ogJMS2MgsLg8cnIRk5YKOor3+rOwdfuZkEqf/NUHu5lXiBQ9lWx/U2JD4IuzcTMJS/l+7A/ZD5YX3YL6ZNKXURdYjsasHz8V3UkBOP2S8lothvI5VyaqQ/KRUStfrnDhALGJUgrrfioGuqfhYeF7x/276d7ZvY1gy90q+d1efzYaMToTBAmc5DszBIRjRs/VJ8xX6XmlL9PRMNQyL4ycu19ZYE9kvsMVwsFgRfLa3zZrH0SsQVmIi1j0Cn5GHEdqc6N4Z0Q699+COdWU54S3+KAIBEVc3yUW3Y/b37WL8AZP3QscFSPlJ3il9KKQrkIz3CJQoJhrDPpjVUFFM6OFBke9QZYMXmLTgONJZczPZEmniYTVDK8eFnaoRkbN1Hhid0Na0xr1SpzR24v0du3yNZ9pTYuy8KuQJJk/M9JoQIR3bKTajxb3WxbVHxCeg+LQodO8BrlUmAaT9QTzzxkCcacvcvmeduD0AJ01OPiKY447F5r4UENuwSsGquLMxtleSrOCNRgqQZpe4mh/Fntjus2wzSaVPy/NZsjKUpGnQG7FhfaxGc7SZmkDIrJBnfM1VPFCKdNS+hV3fkZm2FwsHg6PYBamkA/SE6BUy21laOjE3y7VFWAo7/Nk/o=
  template:
    metadata:
      creationTimestamp: null
      name: amqp-credentials
      namespace: beta
    type: Opaque
