apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mixpanel-keys
  namespace: beta
spec:
  encryptedData:
    MIXPANEL_TOKEN: AgClNuCfRaWNMiNpXQwRpJwsuq9JnvZfkN5uAThS76rYOnVV4LytFCFM/+Pe4P/Q8rg1inqUzyvYyTWPz/od6JEJX4LnESiB4CVClC2PSaix6kXhLBImnS7RNUTedPAe7Q2Ddp6FwkLkvFZf741a7wH5Fj91DsbMUmPWM14v7ecwh/oGHL3UUJANO9wa2Z8VRmnqezansnmP+GnKH14aOvft/JQrg4i8RtsI7qFE+TPjwEFRAw72wIUO56sDCdw+HP2PfMvSfk2ogtvlL07JTh+HKruTi+zJjc8hZCeyFKW3Yb4VMpK6oV4znzQdGMhDvReBN0D/0XdFGskB7oMNrfplDU0C0SpUV1NqlO/Pc/UFB2ulX6uzKTiSmqxPErm1SBPfkND86U2uiPitla20XVdMx1ZrvJDKbzkEQhf8rm24BXJ/Lkf1JWCdtqZvNNbb+Il9+LTQ+fhcd6wf0enke54fRJXT+9xgmIC1mOxS8+hEnS01wi0/vtFDL9YLvP+PGH4btoENd/QrbcGqcSnea64aDsJOD34lxIVGvULcV40pK0hOjVV+MoK4PdCPBxCNSAX1ZMPyD/vFChUDZyCQqgr/p8EIPTQSU5WATeeJG4+KkK4sjBXVSuzJ5f4Ox6aSHTQrUAMHIVgGfUyxBdjwMXhuUYBgjha8TDNo/d2Wdc7ey93xgGXp2tsmCNowmOWY0gncQgLudrgTwiF9x2C6rC5OKkVz/ARo+CV1+RODXaQNDg==
  template:
    metadata:
      creationTimestamp: null
      name: mixpanel-keys
      namespace: beta
    type: Opaque
