apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: mewe/therma-energy-tots-data-consumer:release_32171edf8a1490cc4e3c6276c3c58fd26fd0c507_20230113150333 # {"$imagepolicy": "beta:tots-data-consumer"}
